Repository nomtek/flutter_ai_examples, pull requests merged in 2024-02, with the labels that each got.

#16 Delete localizations from the project
  l10n.yaml
  lib/app/app.dart
  lib/app/home_page.dart
  lib/l10n/app_en.arb
  lib/l10n/l10n.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  pubspec.lock
  pubspec.yaml
Labels: code quality

#19 Book example readme improvements
  lib/mistral_ai_book_search_example/README.md
Labels: documentation

#17 Add readme for mistral chat example
  lib/mistral_ai_chat_example/README.md
Labels: documentation

#18 Add README to LLM as a controller example
  lib/mistral_ai_llm_controller_example/README.md
Labels: documentation

#20 Add readme for mistral summary example
  lib/mistral_ai_summary_example/README.md
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/mistral_ai_summary_example/utils.dart
Labels: documentation

#21 Extract mistral client and mistral tokenizer to separate files
  lib/mistral_ai_book_search_example/book_search.dart
  lib/mistral_ai_book_search_example/mistralai_book_search_page.dart
  lib/mistral_ai_book_search_example/prepare_data.dart
  lib/mistral_ai_chat_example/mistralai_chat_page.dart
  lib/mistral_ai_llm_controller_example/mistral_ai_llm_controller_page.dart
  lib/mistral_ai_summary_example/mistral_client.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/mistral_client/mistral_client.dart
  lib/mistral_tokenizer/mistral_tokenizer.dart
Labels: code quality

#23 Home page design updates
  lib/app/home_page.dart
  lib/app/home_tiles.dart
  lib/app/router.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#22 Setup font and theme for the example app
  assets/fonts/Inter-Black.ttf
  assets/fonts/Inter-Bold.ttf
  assets/fonts/Inter-ExtraBold.ttf
  assets/fonts/Inter-ExtraLight.ttf
  assets/fonts/Inter-Light.ttf
  assets/fonts/Inter-Medium.ttf
  assets/fonts/Inter-Regular.ttf
  assets/fonts/Inter-SemiBold.ttf
  assets/fonts/Inter-Thin.ttf
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/app/app.dart
  lib/app/theme.dart
  lib/main.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#29 Update README to list all examples
  .vscode/launch.json
  README.md
  docs/assets/app_settings_navigation.png
Labels: documentation

#28 App settings page
  devtools_options.yaml
  lib/app/app.dart
  lib/app/app_settings/app_settings.dart
  lib/app/app_settings/app_settings_page.dart
  lib/app/home_page.dart
  lib/app/router.dart
  lib/app/router.g.dart
  lib/app/theme.dart
  lib/main.dart
  lib/mistral_ai_book_search_example/book_search.dart
  lib/mistral_ai_book_search_example/mistralai_book_search_page.dart
  lib/mistral_ai_chat_example/mistralai_chat_page.dart
  lib/mistral_ai_llm_controller_example/mistral_ai_llm_controller_page.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/mistral_client/mistral_client.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#30 24 summary example
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/app/router.dart
  lib/app/theme.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/mistral_ai_summary_example/model.dart
  lib/mistral_ai_summary_example/settings_dialogs.dart
  lib/mistral_ai_summary_example/settings_model.dart
  lib/mistral_ai_summary_example/summary_settings_page.dart
  macos/Podfile.lock
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcworkspace/contents.xcworkspacedata
Labels: code quality

#32 Summary example demo
  docs/assets/text_summary_example_demo.gif
  lib/mistral_ai_summary_example/README.md
Labels: documentation

#34 Update llm controller example
  docs/assets/llm_controller_example_demo.gif
  lib/app/theme.dart
  lib/mistral_ai_llm_controller_example/README.md
  lib/mistral_ai_llm_controller_example/logger_dialog.dart
  lib/mistral_ai_llm_controller_example/mistral_ai_llm_controller_page.dart
  lib/mistral_ai_llm_controller_example/model.dart
Labels: bug, documentation, code quality

#33 Update name of the app in pubspec and all other places
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/nomtek/mistral_ai_chat_example_app/MainActivity.kt
  ios/Runner/Info.plist
  lib/app/app.dart
  lib/app/app_settings/app_settings_page.dart
  lib/app/home_page.dart
  lib/app/home_tiles.dart
  lib/app/router.dart
  lib/main.dart
  lib/mistral_ai_book_search_example/book_search.dart
  lib/mistral_ai_book_search_example/mistralai_book_search_page.dart
  lib/mistral_ai_book_search_example/prepare_data.dart
  lib/mistral_ai_llm_controller_example/mistral_ai_llm_controller_page.dart
  lib/mistral_ai_llm_controller_example/prompt.dart
  lib/mistral_ai_llm_controller_example/utils.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/mistral_ai_summary_example/settings_dialogs.dart
  lib/mistral_ai_summary_example/summary_settings_page.dart
  linux/CMakeLists.txt
  linux/my_application.cc
  macos/Runner.xcodeproj/project.pbxproj
  macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  macos/Runner/Configs/AppInfo.xcconfig
  pubspec.yaml
  test/mistral_tokenizer/mistral_tokenizer_test.dart
  web/index.html
  web/manifest.json
  windows/CMakeLists.txt
  windows/runner/Runner.rc
  windows/runner/main.cpp
Labels: code quality

#35 Improve error handling in the example app
  lib/app/app_settings/app_settings.dart
  lib/app/home_page.dart
  lib/app/home_tiles.dart
  lib/mistral_ai_book_search_example/mistralai_book_search_page.dart
  lib/mistral_ai_chat_example/chat_model.dart
  lib/mistral_ai_chat_example/mistralai_chat_page.dart
  lib/mistral_ai_llm_controller_example/mistral_ai_llm_controller_page.dart
  lib/mistral_ai_summary_example/mistralai_summary_page.dart
  lib/utils/error_message.dart
  lib/utils/snackbar_extension.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile.lock
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: code quality

#37 Update README with the interactive demo
  README.md
Labels: documentation
